# Generated by Django 5.0 on 2023-12-27 06:09

import blog.validators.server_name_validator
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('intro', models.TextField()),
                ('body', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='ServerInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('server_name', models.CharField(db_comment='サーバーの名前 同一名不可', max_length=255, unique=True, validators=[blog.validators.server_name_validator.server_name_validator], verbose_name='サーバー名')),
                ('server_description', models.TextField(db_comment='説明付与', error_messages={'required': '説明を入力してください'})),
                ('server_address', models.CharField(db_comment='サーバーのIPアドレス', max_length=255)),
                ('server_port', models.IntegerField(db_comment='サーバーのポート番号')),
                ('server_user', models.CharField(db_comment='サーバーのユーザー名', max_length=255)),
                ('server_password', models.CharField(db_comment='サーバーのパスワード', max_length=255, verbose_name='サーバーパスワード')),
                ('server_key', models.BinaryField(blank=True, db_comment='サーバーのSSHキーorFTPの秘密鍵', editable=True, null=True)),
                ('server_key_name', models.CharField(blank=True, db_comment='サーバーのSSHキーorFTPの秘密鍵の名前', max_length=255, null=True)),
                ('server_key_password', models.CharField(db_comment='サーバーのSSHキーorFTPの秘密鍵のパスワード', max_length=255)),
                ('comment', models.TextField(blank=True, db_comment='サーバーのコメント(任意)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'server_informations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('family_name', models.CharField(max_length=255)),
                ('given_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('zipcode', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
